# Memo

Link of the dataset:(from Kaggle)
https://www.kaggle.com/datasets/bobbyscience/league-of-legends-diamond-ranked-games-10-min?resource=download

# Overview of the dataset
- The dataset includes the data of 10k ranked games in League of Legends(from high Diamond to low Master) after the first 10 minutes of the game.

- The link is above and I obtained it from kaggle.

- The dataset contains 10,000 observations and 40 predictors. I will randomly choose a sample of 300 observations for my final project. Also, I will choose 10 predictors that I personally consider to be most relevant to the prediction of winning the game.

- The response would be either winning or losing(categorical), and the predictors would have both quantitative(numerical) and categorical values.

- There is no missing data in my chosen dataset.

# Overview of my research questions
I want to predict if a team is able to win the game in league of legends based on their performance after 10 minutes of the game.

My response is whether the team won or lost(1 as win, 0 as lose).

I am thinking of using the classification approach but I am not sure if it is the best choice.

Most useful predictors: team total experience difference(represent the difference in players' levels between two teams) , team total gold difference(represent the difference in player's gold) between two teams)

The goal of my model is to predict if a team is able to win the game based on their performance as a team after 10 minutes of the game(predictive). Since there are so many factors that affect the result of the game, I found this topic to be quite intriguing.

# Project timeline
I would like to start once I get a pass for my memo, and I will try to have my draft finished in 3 weeks so that I will have enough time to get help from the TAs. The revision period should be about 1 week, and then 1 week for final review and corrections. 

# Questions
I am wondering if it is fine to have both categorical predictors and numerical predictors?
And is classification approach the best approach for me since my response is categorical?



